### ISSUE TITLE
建议建议点击扩展图标后立刻转换复制并移除这个点击扩展后的弹出页面

### ISSUE THREAD

**Issue by cxplay** [Mr-houzi/url2md#1]
> 插件很棒!

建议点击扩展图标后立刻转换并复制, 而且目前点击之后会出现以下的页面, 建议移除

![image](https://user-images.githubusercontent.com/62034099/144719838-0a00bd3d-8e9d-4e6c-869c-ccba42923a41.png)

**Comment by Mr-houzi** [comment]
已采纳，后续版本优化

**Comment by Mr-houzi** [comment]
新版popup页提供了标题过滤功能，欢迎体验！

**Comment by cxplay** [comment]
![image](https://user-images.githubusercontent.com/62034099/144751502-3c75a171-fbe7-4445-b4ce-854430f97a5c.png)

然而并没有, 也不能点击后转换复制.

**Comment by cxplay** [comment]
![image](https://user-images.githubusercontent.com/62034099/144751625-b1f61df7-d746-40e7-a992-843dcd9ff617.png)

现在重新安装了一下, 能够跳出这个界面了, 但好像存在一些问题, 有的页面会有多个选项?

**Comment by Mr-houzi** [comment]
> 

需要 clone 新版本，这是过滤后的可选的 title，用于过滤掉某些网站恶心的小尾巴

**Comment by cxplay** [comment]
> > 
> 
> 需要 clone 新版本，这是过滤后的可选的 title，用于过滤掉某些网站恶心的小尾巴

😂原来如此, 我竟一时半会看不出区别来.

**Comment by cxplay** [comment]
我又回来了, 弹出窗口可点击复制的那个区域好小! 希望能够直接整个文本都可以点击.🤣
