### ISSUE TITLE
建议支持 Unicode 编码转换

### ISSUE THREAD

**Issue by cxplay** [Mr-houzi/url2md#2]
对于 URL 有中文和特殊字符的可以进行转换, 可参考以下浏览器扩展:

> [Copy Unicode URLs - Chrome 网上应用店](https://chrome.google.com/webstore/detail/copy-unicode-urls/fnbbfiapefhkicjhecnoepbijhanpkjp)

**Comment by Mr-houzi** [comment]
请提供一下url示例

**Comment by cxplay** [comment]
例如 Wikipedia 的中文页面链接:

> https://zh.wikipedia.org/wiki/微软#法律議題及網際網路（1995年–2007年）

但实际上复制出来是这样的, 因为被自动百分号编码了.

```Markdown
[微软 \- 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E5%BE%AE%E8%BD%AF#%E6%B3%95%E5%BE%8B%E8%AD%B0%E9%A1%8C%E5%8F%8A%E7%B6%B2%E9%9A%9B%E7%B6%B2%E8%B7%AF%EF%BC%881995%E5%B9%B4%E2%80%932007%E5%B9%B4%EF%BC%89)
```

**Comment by Mr-houzi** [comment]
> 例如 Wikipedia 的中文页面链接:
> 
> > [https://zh.wikipedia.org/wiki/微软#法律議題及網際網路（1995年–2007年）](https://zh.wikipedia.org/wiki/%E5%BE%AE%E8%BD%AF#%E6%B3%95%E5%BE%8B%E8%AD%B0%E9%A1%8C%E5%8F%8A%E7%B6%B2%E9%9A%9B%E7%B6%B2%E8%B7%AF%EF%BC%881995%E5%B9%B4%E2%80%932007%E5%B9%B4%EF%BC%89)
> 
> 但实际上复制出来是这样的, 因为被自动百分号编码了.
> 
> ```gfm
> [微软 \- 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E5%BE%AE%E8%BD%AF#%E6%B3%95%E5%BE%8B%E8%AD%B0%E9%A1%8C%E5%8F%8A%E7%B6%B2%E9%9A%9B%E7%B6%B2%E8%B7%AF%EF%BC%881995%E5%B9%B4%E2%80%932007%E5%B9%B4%EF%BC%89)
> ```

采纳，这是个不错的注意

**Comment by Mr-houzi** [comment]
考虑后暂时决定增加此 feature
1. 对应url中存在中文且存在空格时，转码后，编辑器不能很好提示。
![11](https://user-images.githubusercontent.com/26339918/144751521-922ecdd4-52f2-48ee-a619-3e341f17a8c4.png)
2. markdown 显示中注重 title，而无需关注”丑陋的url“。

**Comment by cxplay** [comment]
> 考虑后暂时决定增加此 feature
> 
> 1. 对应url中存在中文且存在空格时，转码后，编辑器不能很好提示。
>    ![11](https://user-images.githubusercontent.com/26339918/144751521-922ecdd4-52f2-48ee-a619-3e341f17a8c4.png)
> 2. markdown 显示中注重 title，而无需关注”丑陋的url“。

1. 可以只编码空格, 很大可能是部分编辑器不能正确渲染, 但我的编辑器能够正常预览带空格的 URL, 可以将 "只编码空格" 作为一个设置项.
   > ![image](https://user-images.githubusercontent.com/62034099/144751940-f2564a3d-c1f2-48b6-9d9b-79ba21f8490b.png)
2. 有时候无法预览渲染而只能阅读源码时会很破坏观感, Markdown 的语法就是为了便于编写格式化, 渲染并不是首要的.

**Comment by Mr-houzi** [comment]
> > 考虑后暂时决定增加此 feature
> > 
> > 1. 对应url中存在中文且存在空格时，转码后，编辑器不能很好提示。
> >    ![11](https://user-images.githubusercontent.com/26339918/144751521-922ecdd4-52f2-48ee-a619-3e341f17a8c4.png)
> > 2. markdown 显示中注重 title，而无需关注”丑陋的url“。
> 
> 1. 可以只编码空格, 很大可能是部分编辑器不能正确渲染, 但我的编辑器能够正常预览带空格的 URL, 可以将 "只编码空格" 作为一个设置项.
>    > ![image](https://user-images.githubusercontent.com/62034099/144751940-f2564a3d-c1f2-48b6-9d9b-79ba21f8490b.png)
> 2. 有时候无法预览渲染而只能阅读源码时会很破坏观感, Markdown 的语法就是为了便于编写格式化, 渲染并不是首要的.

后续考虑作为配置项引入此设定

**Comment by Mr-houzi** [comment]
@cxplay [Release v1.1.0 · Mr-houzi/url2md](https://github.com/Mr-houzi/url2md/releases/tag/v1.1.0) 已采纳，并添加此功能。

**Comment by cxplay** [comment]
> @cxplay [Release v1.1.0 · Mr-houzi/url2md](https://github.com/Mr-houzi/url2md/releases/tag/v1.1.0) 已采纳，并添加此功能。

棒!
