### ISSUE TITLE
增加对知乎回答的适配

### ISSUE THREAD

**Issue by Ray-D-Song** [Mr-houzi/url2md#5]
目前在知乎回答页面只会检测到问题的 url，希望可以检测 #ContentItem AnswerItem 元素来生成回答的 url。

**Comment by Mr-houzi** [comment]
> 目前在知乎回答页面只会检测到问题的 url，希望可以检测 #ContentItem AnswerItem 元素来生成回答的 url。

通过右键的使用方式可以解决你的需求

**Comment by Ray-D-Song** [comment]
试了一下，谢谢
